### ISSUE TITLE
Ignore unsupported algorithms

### ISSUE THREAD

**Issue by centromere** [krdlab/haskell-oidc-client#35]
I am using [Keycloak](https://www.keycloak.org/) as my OIDC provider, and the well-known endpoint advertises `PS384` as a supported signing algorithm. Parsing the JSON [fails in this case](https://github.com/krdlab/haskell-oidc-client/blob/0b88924036fe1e79ed00e5cbcd30016be39f07c4/src/Web/OIDC/Client/Discovery/Provider.hs#L44), however this is not ideal. Would it be possible to ignore unsupported algorithms?

**Comment by sir4ur0n** [comment]
We just started having the same issue: algorithme `PS256` breaks.

* How about using `eitherDecode` instead of `decode` in `Web.OIDC.Client.Discovery#discover`? At least this would help investigating why the library breaks
* At least be able to "not break" when algorithms are unknown? E.g. via environment variable

**Comment by krdlab** [comment]
@centromere @Sir4ur0n 
Thank you for your report and suggestions!

I think the issue was resolved by #36. I will release a new version.

**Comment by krdlab** [comment]
0.5.0.0 released. #37

**Comment by sir4ur0n** [comment]
Excellent, thank you for your work! We have already upgraded 😄
